### PR TITLE
Bump libs/graphicsmagick to 2021 stable versions

### PR DESCRIPTION
**Pull request by czj**
I checked all dependencies for breaking chances but did not see any.

Bringing GraphicsMagick and its dependencies to 2021's stable version brings security, bug fixes and some very useful features (like some color space issues that are fixed) 

Sources :

- https://nasm.us
- http://www.libpng.org/pub/png/libpng.html
- https://www.zlib.net
- https://github.com/libjpeg-turbo/libjpeg-turbo
- http://www.graphicsmagick.org/NEWS.html

### CODE REVIEW

**Comment by brandon-welsch** [comment]
Close this issue, as now external libraries are included in GraphicsMagick sources. Related PR #2

**Comment by czj** [comment]
Great, thanks @brandon-welsch !

Will you document changes on Scalingo's website ? Or document a way to specify a precise version of GraphicsMagick ?

**Comment by brandon-welsch** [comment]
@czj The documentation on the Scalingo website is quite complete in my opinion and does not require any particular change I think.

At the moment it's not possible to specify a specific version for this buildpack.

The way we currently manage this buildpack, we can't get the latest versions without doing a release on our side since imagemagick is downloaded from our s3 buildpacks bucket.

But if you need a more recent version that is not available, do not hesitate to come to the support and ask for the desired version.

I'm creating an issue to improve this buildpack so that you can set a specific version from an environment variable.

**Comment by czj** [comment]
Thanks @brandon-welsch

So we can now use the build pack in production, and it will pickup GM version 1.3.36 ?

**Comment by brandon-welsch** [comment]
@czj Exactly. The current version was specified in the README in the PR #3 😉

**Comment by czj** [comment]
Great, thanks !

**Pull request closed without merging**
